from django.contrib import admin
from .models import City, Station, Route, Stop


admin.site.register(City)
admin.site.register(Station)
admin.site.register(Route)
admin.site.register(Stop)


class StationAdmin(admin.ModelAdmin):
    readonly_fields = ["point"]  # making point field unwrittable in admin, as it's autogenerated
